export const cards = [
  {
    id: 0,
    class: "burger",
    title: "Special burguer",
    image: "./src/images/special burger.jpg",
    price: 8.00,
    description: "the best food in the world ",
  },
  {
    id: 1,
    class: "tacos",
    title: "Mexican tacos",
    image: "./src/images/mexican tacos.jpg",
    price: 17.00,
    description: "the best food in the world ",
  },
  {
    id: 2,
    class: "pizza",
    title: "Pizza",
    image: "./src/images/pizza.jpg",
    price: 20.00,
    description: "the best food in the world ",
  },
  {
    id: 3,
    class: "salmon",
    title: "Salmon",
    image: "./src/images/salmon.jpg",
    price: 55.00,
    description: "the best food in the world ",
  },
  {
    id: 4,
    class: "pancakes",
    title: "Pancakes",
    image: "./src/images/panckques.jpg",
    price: 10.00,
    description: "the best food in the world ",
  },
  {
    id: 5,
    class: "fries",
    title: "French fries",
    image: "./src/images/french fries.jpg",
    price: 25.00,
    description: "the best food in the world ",
  },
  {
    id: 6,
    class: "sandwich",
    title: "Sandwich",
    image: "./src/images/sandwich",
    price: 35.00,
    description: "the best food in the world ",
  },
  {
    id: 7,
    class: "sushi",
    title: "Sushi",
    image: "./src/images/sushi.jpg",
    price: 50.00,
    description: "the best food in the world ",
  },
];
