export const cards = [
  {
    id: 0,
    type: "main course",
    class: "burger",
    title: "Special burguer",
    image: "./src/images/special burger.jpg",
    price: 8.0,
    description: "the best food in the world ",
  },
  {
    id: 1,
    type: "main course",
    class: "tacos",
    title: "Mexican tacos",
    image: "./src/images/mexican tacos.jpg",
    price: 17.0,
    description: "the best food in the world ",
  },
  {
    id: 2,
    type: "main course",
    class: "pizza",
    title: "Pizza",
    image: "./src/images/pizza.jpg",
    price: 20.0,
    description: "the best food in the world ",
  },
  {
    id: 3,
    type: "main course",
    class: "salmon",
    title: "Salmon",
    image: "./src/images/salmon.jpg",
    price: 55.0,
    description: "the best food in the world ",
  },
  {
    id: 4,
    type: "main course",
    class: "pancakes",
    title: "Pancakes",
    image: "./src/images/panckques.jpg",
    price: 10.0,
    description: "the best food in the world ",
  },
  {
    id: 5,
    type: "main course",
    class: "fries",
    title: "French fries",
    image: "./src/images/french fries.jpg",
    price: 25.0,
    description: "the best food in the world ",
  },
  {
    id: 6,
    type: "main course",
    class: "sandwich",
    title: "Sandwich",
    image: "./src/images/sandwich",
    price: 35.0,
    description: "the best food in the world ",
  },
  {
    id: 7,
    type: "main course",
    class: "sushi",
    title: "Sushi",
    image: "./src/images/sushi.jpg",
    price: 50.0,
    description: "the best food in the world ",
  },
  {
    id: 8,
    type: "drinks",
    class: "coca_cola",
    title: "Coca Cola",
    image: "./src/images/COCA-COLA.jpg",
    price: 5.0,
    description: "the best food in the world ",
  },
  {
    id: 9,
    type: "drinks",
    class: "postobon",
    title: "Productos Postobón",
    image: "./src/images/postobon.png",
    price: 3.0,
    description: "the best food in the world ",
  },
  {
    id: 10,
    type: "drinks",
    class: "hatsu",
    title: "Hatsu",
    image: "./src/images/hatsu.png",
    price: 8.0,
    description: "the best food in the world ",
  },
  {
    id: 11,
    type: "drinks",
    class: "limonada",
    title: "Limonada de Coco",
    image: "./src/images/limonada.jpg",
    price: 50.0,
    description: "the best food in the world ",
  },
];
